-- Script for mysql

CREATE DATABASE `dms`;

DROP TABLE IF EXISTS `dms`.`USER`;
CREATE TABLE  `dms`.`USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ENABLED` int(11) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `dms`.`USER_ROLE`;
CREATE TABLE  `dms`.`USER_ROLE` (
  `USER_ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AUTHORITY` varchar(100) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  KEY `FKC6C79929F82A0489` (`USER_ID`),
  CONSTRAINT `FKC6C79929F82A0489` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `dms`.`METADATA`;
CREATE TABLE  `dms`.`METADATA` (
  `METADATA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMMENTS` longtext,
  `CREATED_USER` varchar(255) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `DOCUMENT_FILE_NAME` longtext,
  `SIZE` bigint(20) DEFAULT NULL,
  `DOCUMENT_TYPE` varchar(200) DEFAULT NULL,
  `KEYWORDS` varchar(255) DEFAULT NULL,
  `OWNER` varchar(100) NOT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`METADATA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `dms`.USER(user_id, ENABLED, USERNAME, PASSWORD) values(1,1,'admin','d033e22ae348aeb5660fc2140aec35850c4da997');
insert into `dms`.USER(user_id, ENABLED, USERNAME, PASSWORD) values(2,1,'kelas','741f6931a7deef0883128cb407b31e166432498a');

insert into `dms`.USER_ROLE(USER_ROLE_ID, USER_ID,AUTHORITY) VALUES(1,1,'ROLE_USER');
insert into `dms`.USER_ROLE(USER_ROLE_ID, USER_ID,AUTHORITY) VALUES(2,2,'ROLE_ADMIN');

